import test from 'node:test';import assert from 'node:assert/strict';
import {campaign,comparison,datasetVersion,versions,campaignGate,verifiedAgentVersion,verifiedCampaign} from '../src/lib/campaign-contracts.ts';
import {type Identity} from '../src/lib/contracts.ts';
const uid=(n:number)=>String(n).repeat(8)+'-'+String(n).repeat(4)+'-4'+String(n).repeat(3)+'-8'+String(n).repeat(3)+'-'+String(n).repeat(12);
const user:Identity={username:'demo-admin',actorId:uid(1),organizationId:uid(2),projectId:uid(3),role:'admin',identityProvider:'keycloak',runtime:'java21-spring-boot'};
const scope={organization_id:user.organizationId,project_id:user.projectId};
const meta={resource_key:'release-agent',version:1,content_sha256:'a'.repeat(64),created_at:'2026-10-11T00:00:00Z'};
const agent={...meta,...scope,id:uid(4),definition:{contract:'fixed-scenarios-v1',provider:'synthetic',description:'fixed'}};
const dataset={...meta,...scope,id:uid(5),definition:{contract:'fixed-scenarios-v1',cases:[{id:'required-pass',scenario:'pass',required:true}]}};
function fixture(){return {id:uid(6),...scope,created_at:meta.created_at,requires_approval:true,agent_version_id:agent.id,dataset_version_id:dataset.id,agent_content_sha256:meta.content_sha256,dataset_content_sha256:meta.content_sha256,agentVersion:structuredClone(agent),datasetVersion:structuredClone(dataset),state:'succeeded',decision:'pass',cases:[{caseId:'required-pass',required:true,runId:uid(7),scenario:'pass',provider:'synthetic',state:'succeeded',decision:'pass'}],result:{state:'succeeded',decision:'pass',executionEngine:'java-campaign-aggregate',rules:[{id:'case/required-pass',required:true,status:'pass',reason:'stored'}]}}}
test('immutable versions reject malformed hashes, duplicates, foreign scope and all optional cases',()=>{assert.equal(versions([agent]).length,1);assert.throws(()=>versions([agent,agent]));assert.throws(()=>versions([{...agent,content_sha256:'bad'}]));assert.throws(()=>datasetVersion({...dataset,project_id:uid(9)},user));assert.throws(()=>datasetVersion({...dataset,definition:{...dataset.definition,cases:[{...dataset.definition.cases[0],required:false}]}},user))});
test('campaigns reject cross-version, provider, scope and contradictory aggregate evidence',()=>{const f=fixture();assert.equal(campaign(f,user,f.id).decision,'pass');for(const changed of [{...f,agent_content_sha256:'b'.repeat(64)},{...f,project_id:uid(9)},{...f,cases:[{...f.cases[0],provider:'ollama'}]},{...f,cases:[{...f.cases[0],decision:'block'}]},{...f,result:{...f.result,executionEngine:'python-synthetic'}},{...f,result:{...f.result,rules:[]}}])assert.throws(()=>campaign(changed,user,f.id))});
test('queued and errored campaigns cannot display a passing gate',()=>{const f=fixture();f.state='failed';f.decision='inconclusive';f.cases[0].state='failed';f.cases[0].decision='inconclusive';f.result.state='failed';f.result.decision='inconclusive';f.result.rules[0].status='inconclusive';const record=campaign(f,user,f.id);assert.throws(()=>campaignGate({decision:'pass',deploymentAllowed:true,reason:'bad',signed:false,currentReviewRequired:true,policyEngine:'opa-rego',policyStatus:'evaluated',policyVersion:'1.1.0',policyDigest:'sha256:'+'a'.repeat(64)},record))});
test('comparison refuses mismatched datasets, deployment authority and invented required case ids',()=>{const record=campaign(fixture(),user,uid(6)),v={campaignId:record.id,baselineCampaignId:uid(8),organizationId:user.organizationId,projectId:user.projectId,datasetVersionId:record.dataset_version_id,datasetContentSha256:record.dataset_content_sha256,comparison:{status:'no-regression',newlyFailedRequiredCases:[],unresolvedRequiredCases:[],improvedRequiredCases:[],deploymentAuthority:false}};assert.equal(comparison(v,user,record,uid(8)).deploymentAuthority,false);assert.throws(()=>comparison({...v,datasetVersionId:uid(9)},user,record,uid(8)));assert.throws(()=>comparison({...v,comparison:{...v.comparison,deploymentAuthority:true}},user,record,uid(8)));assert.throws(()=>comparison({...v,comparison:{...v.comparison,status:'regression',newlyFailedRequiredCases:['invented']}},user,record,uid(8)))});

test('browser hashes actual canonical version content before displaying a campaign',async()=>{const a={...agent,definition:{...agent.definition,description:'고정 \n 설명'}},f=fixture();async function digest(value:unknown){const content=new TextEncoder().encode(JSON.stringify(value));return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',content)),b=>b.toString(16).padStart(2,'0')).join('')}a.content_sha256=await digest({contract:a.definition.contract,description:a.definition.description,provider:a.definition.provider});assert.equal((await verifiedAgentVersion(a,user)).content_sha256,a.content_sha256);await assert.rejects(verifiedAgentVersion({...a,definition:{...a.definition,description:'substituted'}},user));f.agentVersion=a;f.agent_content_sha256=a.content_sha256;f.datasetVersion.content_sha256=await digest({cases:[{id:'required-pass',required:true,scenario:'pass'}],contract:'fixed-scenarios-v1'});f.dataset_content_sha256=f.datasetVersion.content_sha256;assert.equal((await verifiedCampaign(f,user,f.id)).id,f.id);await assert.rejects(verifiedCampaign({...f,datasetVersion:{...f.datasetVersion,definition:{...f.datasetVersion.definition,cases:[{...f.datasetVersion.definition.cases[0],scenario:'block'}]}}},user,f.id))});
