import test from 'node:test';import assert from 'node:assert/strict';
import {campaign,comparison,datasetVersion,versions,campaignGate,verifiedAgentVersion,verifiedCampaign,verifiedCampaignArchive} from '../src/lib/campaign-contracts.ts';
import {type Identity} from '../src/lib/contracts.ts';
const uid=(n:number)=>String(n).repeat(8)+'-'+String(n).repeat(4)+'-4'+String(n).repeat(3)+'-8'+String(n).repeat(3)+'-'+String(n).repeat(12);
const user:Identity={username:'demo-admin',actorId:uid(1),organizationId:uid(2),projectId:uid(3),role:'admin',identityProvider:'keycloak',runtime:'java21-spring-boot'};
const scope={organization_id:user.organizationId,project_id:user.projectId};
const meta={resource_key:'release-agent',version:1,content_sha256:'a'.repeat(64),created_at:'2026-10-11T00:00:00Z'};
const agent={...meta,...scope,id:uid(4),definition:{contract:'fixed-scenarios-v1',provider:'synthetic',description:'fixed'}};
const dataset={...meta,...scope,id:uid(5),definition:{contract:'fixed-scenarios-v1',cases:[{id:'required-pass',scenario:'pass',required:true}]}};
function fixture(){return {id:uid(6),...scope,created_at:meta.created_at,requires_approval:true,agent_version_id:agent.id,dataset_version_id:dataset.id,agent_content_sha256:meta.content_sha256,dataset_content_sha256:meta.content_sha256,agentVersion:structuredClone(agent),datasetVersion:structuredClone(dataset),state:'succeeded',decision:'pass',cases:[{caseId:'required-pass',required:true,runId:uid(7),scenario:'pass',provider:'synthetic',state:'succeeded',decision:'pass'}],result:{state:'succeeded',decision:'pass',executionEngine:'java-campaign-aggregate',rules:[{id:'case/required-pass',required:true,status:'pass',reason:'stored'}]}}}
test('immutable versions reject malformed hashes, duplicates, foreign scope and all optional cases',()=>{assert.equal(versions([agent]).length,1);assert.throws(()=>versions([agent,agent]));assert.throws(()=>versions([{...agent,content_sha256:'bad'}]));assert.throws(()=>datasetVersion({...dataset,project_id:uid(9)},user));assert.throws(()=>datasetVersion({...dataset,definition:{...dataset.definition,cases:[{...dataset.definition.cases[0],required:false}]}},user))});
test('campaigns reject cross-version, provider, scope and contradictory aggregate evidence',()=>{const f=fixture();assert.equal(campaign(f,user,f.id).decision,'pass');for(const changed of [{...f,agent_content_sha256:'b'.repeat(64)},{...f,project_id:uid(9)},{...f,cases:[{...f.cases[0],provider:'ollama'}]},{...f,cases:[{...f.cases[0],decision:'block'}]},{...f,result:{...f.result,executionEngine:'python-synthetic'}},{...f,result:{...f.result,rules:[]}}])assert.throws(()=>campaign(changed,user,f.id))});
test('queued and errored campaigns cannot display a passing gate',()=>{const f=fixture();f.state='failed';f.decision='inconclusive';f.cases[0].state='failed';f.cases[0].decision='inconclusive';f.result.state='failed';f.result.decision='inconclusive';f.result.rules[0].status='inconclusive';const record=campaign(f,user,f.id);assert.throws(()=>campaignGate({decision:'pass',deploymentAllowed:true,reason:'bad',signed:false,currentReviewRequired:true,policyEngine:'opa-rego',policyStatus:'evaluated',policyVersion:'1.1.0',policyDigest:'sha256:'+'a'.repeat(64)},record))});
test('comparison refuses mismatched datasets, deployment authority and invented required case ids',()=>{const record=campaign(fixture(),user,uid(6)),v={campaignId:record.id,baselineCampaignId:uid(8),organizationId:user.organizationId,projectId:user.projectId,datasetVersionId:record.dataset_version_id,datasetContentSha256:record.dataset_content_sha256,comparison:{status:'no-regression',newlyFailedRequiredCases:[],unresolvedRequiredCases:[],improvedRequiredCases:[],deploymentAuthority:false}};assert.equal(comparison(v,user,record,uid(8)).deploymentAuthority,false);assert.throws(()=>comparison({...v,datasetVersionId:uid(9)},user,record,uid(8)));assert.throws(()=>comparison({...v,comparison:{...v.comparison,deploymentAuthority:true}},user,record,uid(8)));assert.throws(()=>comparison({...v,comparison:{...v.comparison,status:'regression',newlyFailedRequiredCases:['invented']}},user,record,uid(8)))});

test('browser hashes actual canonical version content before displaying a campaign',async()=>{const a={...agent,definition:{...agent.definition,description:'고정 \n 설명'}},f=fixture();async function digest(value:unknown){const content=new TextEncoder().encode(JSON.stringify(value));return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',content)),b=>b.toString(16).padStart(2,'0')).join('')}a.content_sha256=await digest({contract:a.definition.contract,description:a.definition.description,provider:a.definition.provider});assert.equal((await verifiedAgentVersion(a,user)).content_sha256,a.content_sha256);await assert.rejects(verifiedAgentVersion({...a,definition:{...a.definition,description:'substituted'}},user));f.agentVersion=a;f.agent_content_sha256=a.content_sha256;f.datasetVersion.content_sha256=await digest({cases:[{id:'required-pass',required:true,scenario:'pass'}],contract:'fixed-scenarios-v1'});f.dataset_content_sha256=f.datasetVersion.content_sha256;assert.equal((await verifiedCampaign(f,user,f.id)).id,f.id);await assert.rejects(verifiedCampaign({...f,datasetVersion:{...f.datasetVersion,definition:{...f.datasetVersion.definition,cases:[{...f.datasetVersion.definition.cases[0],scenario:'block'}]}}},user,f.id))});

async function archiveFixture(){const f=fixture();async function hash(value:unknown){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value)))),b=>b.toString(16).padStart(2,'0')).join('')}f.agentVersion.content_sha256=await hash({contract:'fixed-scenarios-v1',description:'fixed',provider:'synthetic'});f.agent_content_sha256=f.agentVersion.content_sha256;f.datasetVersion.content_sha256=await hash({cases:[{id:'required-pass',required:true,scenario:'pass'}],contract:'fixed-scenarios-v1'});f.dataset_content_sha256=f.datasetVersion.content_sha256;const record=await verifiedCampaign(f,user,f.id),doc={schemaVersion:2,kind:'campaign-evidence',deploymentAuthority:false,campaign:f,childArchives:[{runId:uid(7),contentSha256:'b'.repeat(64),contentBytes:100,storageVersion:'child-v1'}]};async function proof(value:unknown){const content=JSON.stringify(value),bytes=new TextEncoder().encode(content);return {campaignId:f.id,organizationId:user.organizationId,projectId:user.projectId,integrityVerified:true,storageEngine:'minio',contentSha256:await hash(value),contentBytes:bytes.length,storageVersion:'parent-v1',contentBase64:Buffer.from(bytes).toString('base64')}}return {record,doc,proof}}
test('campaign archive verifies actual parent bytes and exact version and child archive bindings',async()=>{const {record,doc,proof}=await archiveFixture(),value=await proof(doc);assert.equal((await verifiedCampaignArchive(value,user,record)).childArchives[0].storageVersion,'child-v1');await assert.rejects(verifiedCampaignArchive({...value,contentSha256:'0'.repeat(64)},user,record));await assert.rejects(verifiedCampaignArchive(await proof({...doc,childArchives:[{...doc.childArchives[0],runId:uid(8)}]}),user,record));await assert.rejects(verifiedCampaignArchive({...value,campaignId:uid(9)},user,record))});
test('frozen campaign evidence cannot assert deployment permission or substitute agent content',async()=>{const {record,doc,proof}=await archiveFixture();await assert.rejects(verifiedCampaignArchive(await proof({...doc,deploymentAuthority:true}),user,record));await assert.rejects(verifiedCampaignArchive(await proof({...doc,campaign:{...doc.campaign,agentVersion:{...doc.campaign.agentVersion,definition:{...doc.campaign.agentVersion.definition,description:'changed'}}}}),user,record));await assert.rejects(verifiedCampaignArchive(await proof({...doc,gate:{deploymentAllowed:true}}),user,record))});

test('new agent contracts hash actual fixed execution profiles and reject profile substitution',async()=>{
 function canonical(v:unknown):unknown{if(Array.isArray(v))return v.map(canonical);if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([k,x])=>[k,canonical(x)]));return v}
 async function hash(v:unknown){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(canonical(v))))),x=>x.toString(16).padStart(2,'0')).join('')}
 const profile={schemaVersion:1,contract:'fixed-execution-profile-v1',provider:'synthetic',implementationSha256:'c'.repeat(64),profileVerifierSha256:'d'.repeat(64),executionDeadlineSeconds:120,maxAttempts:1,arbitraryCodeAllowed:false,callerSelectedUrlAllowed:false};
 const definition={contract:'fixed-scenarios-v2',provider:'synthetic',description:'profile-bound',executionProfile:profile,executionProfileSha256:await hash(profile)},value={...agent,definition,content_sha256:await hash(definition)};
 assert.equal((await verifiedAgentVersion(value,user)).definition.executionProfileSha256,definition.executionProfileSha256);
 const changed={...definition,executionProfile:{...profile,implementationSha256:'e'.repeat(64)}};await assert.rejects(verifiedAgentVersion({...value,definition:changed,content_sha256:await hash(changed)},user));
 const unsafe={...definition,executionProfile:{...profile,maxAttempts:2}};await assert.rejects(verifiedAgentVersion({...value,definition:unsafe,content_sha256:await hash(unsafe)},user));
});
