import test from 'node:test';import assert from 'node:assert/strict';
import {identity,detail,gate,runs,RequestScope,authInfo,archivedEvidence,similarEvidence,logoutRedirect,identityLogoutUrl} from '../src/lib/contracts.ts';
import {proxyPath,sameOrigin,sessionCookies,oauthQuery,oidcRedirect} from '../src/lib/proxy-policy.ts';
const organizationId='11111111-1111-4111-8111-111111111111',projectId='22222222-2222-4222-8222-222222222222',id='33333333-3333-4333-8333-333333333333';
const user=identity({username:'demo-admin',organizationId,projectId,actorId:id,role:'admin',identityProvider:'local-demo',runtime:'java21-spring-boot'});
const policy={policyEngine:'opa-rego',policyStatus:'evaluated',policyVersion:'1.0.0',policyDigest:'sha256:'+'a'.repeat(64)};
const record={id,scenario:'pass',requires_approval:true,state:'succeeded',decision:'pass',created_at:'2026-10-10T06:00:00Z'};
const data={...record,organization_id:organizationId,project_id:projectId,result:{state:'succeeded',decision:'pass',rules:[{id:'required-output',required:true,status:'pass',reason:'Synthetic'}],executionEngine:'java-synthetic'}};
test('archived bytes must match digest scope selected result and recorded version',async()=>{const selected=detail(data,user,id),document={schemaVersion:1,runId:id,organizationId,projectId,scenario:'pass',result:selected.result},bytes=new TextEncoder().encode(JSON.stringify(document));const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');const value={runId:id,organizationId,projectId,contentSha256:digest,contentBytes:bytes.length,storageVersion:'stored-version',integrityVerified:true,storageEngine:'minio',contentBase64:Buffer.from(bytes).toString('base64')};assert.equal((await archivedEvidence(value,user,selected)).contentSha256,digest);await assert.rejects(()=>archivedEvidence({...value,contentSha256:'a'.repeat(64)},user,selected));await assert.rejects(()=>archivedEvidence({...value,projectId:id},user,selected));await assert.rejects(()=>archivedEvidence({...value,storageVersion:'null'},user,selected));await assert.rejects(()=>archivedEvidence(value,user,{...selected,result:{...selected.result,rules:[]}}))});
test('OIDC configuration cannot choose an external login or logout URL',()=>{assert.equal(authInfo({identityProvider:'keycloak',loginPath:'/backend/oauth2/authorization/keycloak',objectStorage:'minio'}).identityProvider,'keycloak');assert.throws(()=>authInfo({identityProvider:'keycloak',loginPath:'https://evil.invalid'}));assert.equal(identity({...user,identityProvider:'keycloak'}).identityProvider,'keycloak');assert.equal(logoutRedirect({authenticated:false,logoutUrl:identityLogoutUrl},'keycloak'),identityLogoutUrl);assert.throws(()=>logoutRedirect({authenticated:false,logoutUrl:'https://evil.invalid'},'keycloak'))});
test('only stateful OAuth callback parameters and fixed redirects are accepted',()=>{assert.equal(proxyPath(['oauth2','authorization','keycloak'],'GET'),'/oauth2/authorization/keycloak');assert.throws(()=>proxyPath(['oauth2','authorization','keycloak'],'POST'));assert.throws(()=>oauthQuery('/api/me',new URLSearchParams('code=abcdefgh')));assert.throws(()=>oauthQuery('/login/oauth2/code/keycloak',new URLSearchParams('code=abcdefgh&state=abcdefgh&state=duplicate')));assert.throws(()=>oauthQuery('/login/oauth2/code/keycloak',new URLSearchParams('code=abcdefgh&state=abcdefgh&iss=https://evil.invalid')));assert.ok(oauthQuery('/login/oauth2/code/keycloak',new URLSearchParams('code=abcdefgh&state=abcdefgh')).startsWith('?'));assert.equal(oidcRedirect('/login/oauth2/code/keycloak','http://127.0.0.1:4320/'),'http://127.0.0.1:4320/');assert.throws(()=>oidcRedirect('/login/oauth2/code/keycloak','http://127.0.0.1:4320/evil'));assert.throws(()=>oidcRedirect('/oauth2/authorization/keycloak','https://evil.invalid'))});
test('recorded tenant and selected run must match before displaying evidence',()=>{assert.equal(detail(data,user,id).result.rules.length,1);assert.throws(()=>detail({...data,organization_id:id},user,id));assert.throws(()=>detail(data,user,projectId));assert.throws(()=>detail({...data,result:{...data.result,decision:'block'}},user,id))});
test('contradictory or signed-as-current gate responses are refused',()=>{const run=runs([record])[0];const value={...policy,decision:'pass',deploymentAllowed:true,reason:'Synthetic only',signed:false,currentReviewRequired:true};assert.equal(gate(value,run).deploymentAllowed,true);assert.throws(()=>gate({...value,decision:'block'},run));assert.throws(()=>gate({...value,signed:true},run));assert.throws(()=>gate({...value,currentReviewRequired:false},run));assert.throws(()=>gate(value,{...run,decision:'inconclusive'}))});
test('duplicates, malformed states and nonboolean permissions are refused',()=>{assert.throws(()=>runs([record,record]));assert.throws(()=>runs([{...record,requires_approval:'true'}]));assert.throws(()=>runs([{...record,state:'queued'}]));assert.throws(()=>identity({...user,role:'owner'}))});
test('scope changes invalidate delayed responses',()=>{const scope=new RequestScope(),first=scope.next();assert.equal(scope.current(first),true);const second=scope.next();assert.equal(scope.current(first),false);assert.equal(scope.current(second),true)});
test('queued admissions cannot display an allowing verdict',()=>{const queued=runs([{...record,state:'queued',decision:'inconclusive'}])[0];assert.equal(queued.state,'queued');assert.throws(()=>gate({...policy,decision:'pass',deploymentAllowed:true,reason:'Invalid',signed:false,currentReviewRequired:true},queued));const scope=new RequestScope();assert.equal(scope.capture(),0);scope.next();assert.equal(scope.current(0),false)});
test('proxy only permits bounded known API paths and methods',()=>{assert.equal(proxyPath(['runs',id,'gate'],'GET'),'/api/runs/'+id+'/gate');assert.throws(()=>proxyPath(['runs',id,'gate'],'POST'));assert.throws(()=>proxyPath(['..','actuator'],'GET'));assert.throws(()=>proxyPath(['http:','evil'],'GET'));assert.throws(()=>proxyPath(['login'],'GET'));assert.throws(()=>proxyPath(['runs'],'DELETE'));assert.equal(proxyPath(['gate-trust'],'GET'),'/api/gate-trust');assert.throws(()=>proxyPath(['gate-trust'],'POST'));assert.equal(proxyPath(['campaigns',id,'receipts'],'POST'),'/api/campaigns/'+id+'/receipts');assert.equal(proxyPath(['campaigns',id,'receipts',id],'GET'),'/api/campaigns/'+id+'/receipts/'+id);assert.throws(()=>proxyPath(['campaigns',id,'receipts',id],'POST'));assert.equal(proxyPath(['campaigns',id,'receipts',id,'bundle'],'GET'),'/api/campaigns/'+id+'/receipts/'+id+'/bundle');assert.throws(()=>proxyPath(['campaigns',id,'receipts',id,'bundle'],'POST'))});
test('foreign origins and unrelated legacy cookies are not forwarded',()=>{assert.equal(sameOrigin('http://127.0.0.1:4320','http://127.0.0.1:4320/backend/runs'),true);assert.equal(sameOrigin('http://evil.invalid','http://127.0.0.1:4320/backend/runs'),false);assert.equal(sameOrigin(null,'http://127.0.0.1:4320/backend/runs'),false);assert.equal(sessionCookies('legacy=private; AGENTTRUST_STACK_SESSION=ABCD.123; other=hidden'),'AGENTTRUST_STACK_SESSION=ABCD.123');assert.equal(sessionCookies('AGENTTRUST_STACK_SESSION=bad%0a'),'')});

test('similarity results stay scoped bounded ordered and cannot assert deployment authority',()=>{const selected=detail(data,user,id),other='44444444-4444-4444-8444-444444444444';const value={runId:id,organizationId,projectId,featureVersion:'rule-features-v1',dimensions:64,searchEngine:'pgvector-cosine',deploymentAuthority:false,matches:[{runId:other,state:'succeeded',decision:'pass',scenario:'pass',score:0.8}]};assert.equal(similarEvidence(value,user,selected)[0].score,0.8);for(const invalid of [{...value,projectId:other},{...value,deploymentAuthority:true},{...value,matches:[...value.matches,...value.matches]},{...value,matches:[{...value.matches[0],runId:id}]},{...value,matches:[{...value.matches[0],score:Infinity}]},{...value,matches:[{...value.matches[0],score:0.5},{...value.matches[0],runId:'55555555-5555-4555-8555-555555555555',score:0.9}]}])assert.throws(()=>similarEvidence(invalid,user,selected))});

test("provider admission and returned engine must agree",()=>{const value={...data,provider:"ollama",result:{...data.result,executionEngine:"python-ollama"}};assert.equal(detail(value,user,id).provider,"ollama");assert.throws(()=>detail({...value,result:data.result},user,id));assert.throws(()=>detail({...data,provider:"outside"},user,id));assert.throws(()=>detail({...value,provider:"openai"},user,id))});
