import test from 'node:test';import assert from 'node:assert/strict';
import {generateKeyPairSync,sign,createHash} from 'node:crypto';
import {verifiedReceipt,receiptIds} from '../src/lib/receipt-contracts.ts';
import {type Campaign,type CampaignArchive,campaignGate} from '../src/lib/campaign-contracts.ts';
import {type Identity} from '../src/lib/contracts.ts';
const id=(n:number)=>String(n).repeat(8)+'-'+String(n).repeat(4)+'-4'+String(n).repeat(3)+'-8'+String(n).repeat(3)+'-'+String(n).repeat(12);
const user:Identity={username:'fixture',actorId:id(1),organizationId:id(2),projectId:id(3),role:'admin',identityProvider:'keycloak',runtime:'java21-spring-boot'};
const record={id:id(4),organization_id:id(2),project_id:id(3),requires_approval:true,agent_version_id:id(5),dataset_version_id:id(6),agent_content_sha256:'a'.repeat(64),dataset_content_sha256:'b'.repeat(64),state:'succeeded',decision:'pass',agentVersion:{definition:{provider:'synthetic'}}} as Campaign;
const archive:CampaignArchive={contentSha256:'c'.repeat(64),contentBytes:500,storageVersion:'parent-version',childArchives:[{runId:id(7),contentSha256:'d'.repeat(64),contentBytes:200,storageVersion:'child-version'}]};
const observedGate={decision:'pass',deploymentAllowed:true,reason:'Historical approval',signed:false,currentReviewRequired:true,policyEngine:'opa-rego',policyStatus:'evaluated',policyVersion:'1.1.0',policyDigest:'sha256:'+'e'.repeat(64)};
function fixture(){const pair=generateKeyPairSync('ed25519'),der=pair.publicKey.export({type:'spki',format:'der'}),keyId=createHash('sha256').update(der).digest('hex'),trust={keyId,publicKeySpkiBase64:der.toString('base64'),signatureAlgorithm:'Ed25519',trustDomain:'agenttrust-local-development',productionKey:false};
 const payload={schemaVersion:1,kind:'campaign-gate-observation',trustDomain:trust.trustDomain,currentDeploymentAuthority:false,receiptId:id(8),campaignId:record.id,organizationId:user.organizationId,projectId:user.projectId,actorId:user.actorId,issuedAt:'2026-10-11T00:00:00.123456Z',note:'historical',agentVersionId:record.agent_version_id,datasetVersionId:record.dataset_version_id,agentContentSha256:record.agent_content_sha256,datasetContentSha256:record.dataset_content_sha256,evaluationState:record.state,evaluationDecision:record.decision,observedGate,latestReview:{id:id(9),actorId:user.actorId,decision:'approved',sequence:1,policyVersion:observedGate.policyVersion,policyDigest:observedGate.policyDigest},campaignArchive:{contentSha256:archive.contentSha256,contentBytes:archive.contentBytes,storageVersion:archive.storageVersion},childArchives:archive.childArchives};
 function frame(value:unknown){const bytes=Buffer.from(JSON.stringify(value));return {receiptId:payload.receiptId,campaignId:record.id,organizationId:user.organizationId,projectId:user.projectId,keyId,payloadBase64:bytes.toString('base64'),payloadSha256:createHash('sha256').update(bytes).digest('hex'),payloadBytes:bytes.length,signatureBase64:sign(null,bytes,pair.privateKey).toString('base64'),signatureAlgorithm:'Ed25519',trustDomain:trust.trustDomain,signatureVerified:true,currentDeploymentAuthority:false}}
 return {trust,payload,frame};}
test('actual browser Ed25519 validates historical approval while current rejection remains denied',async()=>{const {trust,payload,frame}=fixture(),receipt=await verifiedReceipt(frame(payload),trust,user,record,archive);assert.equal(receipt.observedGate.deploymentAllowed,true);assert.equal(receipt.currentDeploymentAuthority,false);const current=campaignGate({...observedGate,decision:'block',deploymentAllowed:false,reason:'Latest rejection'},record);assert.equal(current.deploymentAllowed,false);assert.equal(receipt.observedGate.deploymentAllowed,true)});
test('tampered bytes and substituted public key are rejected by actual signature verification',async()=>{const {trust,payload,frame}=fixture(),signed=frame(payload),other=fixture();const changed=Buffer.from(JSON.stringify({...payload,note:'tampered'}));await assert.rejects(verifiedReceipt({...signed,payloadBase64:changed.toString('base64'),payloadSha256:createHash('sha256').update(changed).digest('hex'),payloadBytes:changed.length},trust,user,record,archive));await assert.rejects(verifiedReceipt({...signed,keyId:other.trust.keyId},other.trust,user,record,archive))});
test('even genuinely signed payload cannot substitute scope archive policy review or current authority',async()=>{const {trust,payload,frame}=fixture();for(const changed of [{...payload,currentDeploymentAuthority:true},{...payload,projectId:id(9)},{...payload,campaignArchive:{...payload.campaignArchive,storageVersion:'shadow'}},{...payload,latestReview:null},{...payload,latestReview:{...payload.latestReview,decision:'rejected'}},{...payload,latestReview:{...payload.latestReview,policyDigest:'sha256:'+'f'.repeat(64)}}])await assert.rejects(verifiedReceipt(frame(changed),trust,user,record,archive));assert.throws(()=>receiptIds([{id:id(8)},{id:id(8)}]))});
