import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {hash} from '../packages/contracts/hash.js';
import {acceptanceModes} from '../scripts/acceptance-profile.mjs';
import {inspectAcceptanceReadiness} from '../scripts/acceptance-readiness.mjs';
async function fixture(reuse=[]){const profile=JSON.parse(await readFile(new URL('../examples/connector-contract/acceptance-profile.json',import.meta.url),'utf8')),scope={organizationId:randomUUID(),projectId:randomUUID()},catalog={agent:[],dataset:[],policy:[]},versions=new Map(),calls=[];
 for(const [mode] of acceptanceModes){const data={name:'Synthetic '+mode,mode},id=randomUUID(),contentHash=hash(data);catalog.agent.push({id,name:data.name,mode,contentHash});versions.set(id,{id,kind:'agent',data,contentHash});}for(const kind of reuse){const data=profile[kind],id=randomUUID(),contentHash=hash(data);catalog[kind].push({id,name:data.name,contentHash});versions.set(id,{id,kind,data:structuredClone(data),contentHash});}
 const operations={observedAt:'2026-10-06T00:00:00Z',worker:{state:'recent'},versionCapacity:{scope:'organization',organizationId:scope.organizationId,used:9,limit:1000,remaining:991},executionCapacity:{scope:'organization',organizationId:scope.organizationId,retained:{used:20,limit:10000,remaining:9980},active:{used:0,limit:10,remaining:10}}};return {profile,scope,operations,catalog,versions,calls,call:async(path,body)=>{assert.equal(body,undefined);calls.push(path);if(path==='/v1/catalog')return catalog;assert.match(path,/^\/v1\/versions\/[a-f0-9-]{36}$/);return structuredClone(versions.get(path.split('/').at(-1)));}};
}
test('readiness plans zero, one and two immutable criterion registrations without business writes',async()=>{for(const reuse of [[],['dataset'],['dataset','policy']]){const f=await fixture(reuse),r=await inspectAcceptanceReadiness(f);assert.equal(r.completed,true);assert.equal(r.versionCapacityPreflight.requestedVersions,2-reuse.length);assert.equal(r.agentVersionsVerified,5);assert.equal(r.cases,2);assert.equal(r.rules,5);assert.equal(r.runsCreated,0);assert.equal(r.businessDataWrites,false);assert.equal(r.releaseGateEvaluated,false);assert.equal(f.calls.length,6+reuse.length);}});
test('readiness refuses insufficient or foreign capacities and stale workers before version reads',async()=>{for(const mutate of [f=>f.operations.executionCapacity.retained.remaining=5,f=>f.operations.executionCapacity.organizationId=randomUUID(),f=>f.operations.worker.state='stale',f=>{f.operations.versionCapacity.used=999;f.operations.versionCapacity.remaining=1;},f=>f.operations.versionCapacity.organizationId=randomUUID()]){const f=await fixture();mutate(f);const r=await inspectAcceptanceReadiness(f);assert.equal(r.completed,false);assert.equal(r.failed,true);assert.ok(f.calls.length<=1);assert.ok(['execution-capacity','worker','version-capacity'].includes(r.failedStage));}});
test('readiness accepts full version quota only with exact verified criterion reuse',async()=>{const f=await fixture(['dataset','policy']);f.operations.versionCapacity.used=1000;f.operations.versionCapacity.remaining=0;let r=await inspectAcceptanceReadiness(f);assert.equal(r.completed,true);f.catalog.policy[0].contentHash='0'.repeat(64);f.calls.length=0;r=await inspectAcceptanceReadiness(f);assert.equal(r.completed,false);assert.equal(r.versionCapacityPreflight.requestedVersions,1);assert.deepEqual(f.calls,['/v1/catalog']);});
test('readiness rejects stored agent or criterion mismatches and never repairs them by writing',async()=>{for(const kind of ['agent','dataset','policy'])for(const change of [v=>v.id=randomUUID(),v=>v.kind='invalid',v=>v.contentHash='0'.repeat(64),v=>v.data.name='Altered criterion']){const f=await fixture(['dataset','policy']),row=f.catalog[kind][0];change(f.versions.get(row.id));const r=await inspectAcceptanceReadiness(f);assert.equal(r.completed,false);assert.equal(r.failedStage,kind==='agent'?'agent-versions':'criteria-versions');assert.equal(r.runsCreated,0);assert.ok(!JSON.stringify(r).includes('Altered criterion'));}});

test('readiness binds every valid plan to canonical input without exposing draft names',async()=>{const f=await fixture(['dataset','policy']),original=await inspectAcceptanceReadiness(f);assert.equal(original.profileHash,hash(f.profile));const reordered=Object.fromEntries(Object.entries(f.profile).reverse());assert.equal((await inspectAcceptanceReadiness({...f,profile:reordered})).profileHash,original.profileHash);f.profile.policy.name='Private synthetic edited draft';const edited=await inspectAcceptanceReadiness(f);assert.equal(edited.profileHash,hash(f.profile));assert.notEqual(edited.profileHash,original.profileHash);assert.equal(edited.criteria.policy.reused,false);assert.ok(!JSON.stringify(edited).includes(f.profile.policy.name));f.operations.worker.state='stale';const blocked=await inspectAcceptanceReadiness(f);assert.equal(blocked.completed,false);assert.equal(blocked.profileHash,hash(f.profile));assert.equal(blocked.businessDataWrites,false);});
