import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,mkdtemp,writeFile,rm} from 'node:fs/promises';
import {join,resolve,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';
import {compareRecordedConnectors} from '../packages/evaluator/connector-compare.js';
import {parseCompareFiles} from '../scripts/compare-connector-evidence.mjs';
async function input(){const values=Object.fromEntries(await Promise.all(['dataset','policy','trace'].map(async name=>[name,JSON.parse(await readFile(new URL('../examples/connector-contract/'+name+'.json',import.meta.url),'utf8'))])));return {dataset:values.dataset,policy:values.policy,baseline:values.trace,candidate:structuredClone(values.trace)};}
async function fixture(t){const dir=await mkdtemp(join(process.cwd(),'.local','connector-compare-test-'));t.after(async()=>{assert.ok(resolve(dir).startsWith(resolve(process.cwd(),'.local')+sep));await rm(dir,{recursive:true,force:true});});return dir;}
const cli=(args,extra=[])=>spawnSync(process.execPath,[...extra,'scripts/compare-connector-evidence.mjs',...args],{encoding:'utf8',windowsHide:true,timeout:10000});
test('recorded comparison binds each version independently and compares dataset order without mutating records',async()=>{
 const data=await input();data.candidate.agentVersionId='synthetic-candidate';for(const entry of data.candidate.entries)entry.request.agentVersionId='synthetic-candidate';data.candidate.entries.reverse();const before=JSON.stringify(data),r=compareRecordedConnectors(data);assert.equal(r.comparisonPassed,true);assert.equal(r.comparable,true);assert.equal(r.regressions,0);assert.deepEqual(r.changes,[]);assert.equal(r.deploymentAllowed,false);assert.equal(r.releaseGateEvaluated,false);assert.equal(r.recordedSourceVerified,false);assert.equal(JSON.stringify(data),before);
});
test('optional rule regression blocks comparison even when candidate evaluation still passes',async()=>{
 const data=await input();data.dataset.cases[0].rules.push({id:'optional-marker',type:'contains',value:'administrator',required:false});data.policy.minimumPassRate=0.8;data.candidate.entries[0].response.output='Synthetic refund requests require order verification and review.';const r=compareRecordedConnectors(data);assert.equal(r.candidateDecision,'pass');assert.equal(r.comparisonDecision,'block');assert.equal(r.regressions,1);assert.deepEqual(r.changes,[{caseNumber:1,ruleNumber:4,before:'pass',after:'fail',regression:true}]);
});
test('a complete failing baseline can improve but a failing candidate cannot pass comparison',async()=>{
 const data=await input();data.baseline.entries[0].response.output='Synthetic failed response';let r=compareRecordedConnectors(data);assert.equal(r.baselineDecision,'block');assert.equal(r.comparisonPassed,true);assert.equal(r.regressions,0);assert.ok(r.changes.length>0);[data.baseline,data.candidate]=[data.candidate,data.baseline];r=compareRecordedConnectors(data);assert.equal(r.comparisonDecision,'block');assert.equal(r.regressions,1);
});
test('incomplete or malformed evidence on either side makes comparison inconclusive without mock fallback',async()=>{
 for(const side of ['baseline','candidate'])for(const kind of ['missing','malformed','empty']){const data=await input();if(kind==='missing')delete data[side].entries[0].response;if(kind==='malformed')data[side].entries[0].response={};if(kind==='empty')data[side].entries=[];const r=compareRecordedConnectors(data);assert.equal(r.comparable,false);assert.equal(r.comparisonDecision,'inconclusive');assert.equal(r.comparisonPassed,false);assert.equal(r.deploymentAllowed,false);}
});
test('comparison rejects mismatched requests and redacts evaluation bodies and identifiers',async()=>{
 const data=await input();data.dataset.name='private-label-canary';data.dataset.cases[0].id='private-case-canary';data.dataset.cases[0].input='private-input-canary';data.dataset.cases[0].rules[0].id='private-rule-canary';for(const side of ['baseline','candidate']){data[side].entries[0].request.caseId='private-case-canary';data[side].entries[0].request.input='private-input-canary';}data.candidate.entries[0].response.output='private-output-canary';const r=compareRecordedConnectors(data);assert.equal(r.comparisonDecision,'block');assert.ok(!JSON.stringify(r).includes('canary'));data.candidate.entries[0].request.input='different-input';assert.throws(()=>compareRecordedConnectors(data));
});
test('actual comparison CLI distinguishes regression, incomplete evidence and invalid input',async t=>{
 const dir=await fixture(t),data=await input(),names=['dataset','policy','baseline','candidate'],args=names.flatMap(name=>['--'+name,join(dir,name+'.json')]);async function save(){for(const name of names)await writeFile(join(dir,name+'.json'),JSON.stringify(data[name]));}await save();let result=cli(args);assert.equal(result.status,0);assert.equal(JSON.parse(result.stdout).syntheticExample,false);data.candidate.entries[0].response.output='private-output-canary';await save();result=cli(args);assert.equal(result.status,1);assert.equal(JSON.parse(result.stdout).comparisonDecision,'block');assert.ok(!result.stdout.includes('canary'));delete data.candidate.entries[0].response;await save();result=cli(args);assert.equal(result.status,1);assert.equal(JSON.parse(result.stdout).comparisonDecision,'inconclusive');data.candidate.entries[0].request.input='private-input-canary';await save();result=cli(args);assert.equal(result.status,2);assert.equal(JSON.parse(result.stdout).failedStage,'comparison');assert.ok(!result.stdout.includes('canary'));assert.equal(result.stderr,'');
});
test('comparison example runs with network entry points disabled and rejects ambiguous options',async t=>{
 const dir=await fixture(t),guard=join(dir,'guard.mjs');await writeFile(guard,"import https from 'node:https';import dns from 'node:dns';import {syncBuiltinESMExports} from 'node:module';https.request=()=>{throw Error('Network prohibited');};dns.promises.lookup=()=>{throw Error('DNS prohibited');};globalThis.fetch=()=>{throw Error('Network prohibited');};syncBuiltinESMExports();");const result=cli([],['--import',pathToFileURL(guard).href]);assert.equal(result.status,0);const r=JSON.parse(result.stdout);assert.equal(r.networkRequestsMade,0);assert.equal(r.syntheticExample,true);assert.equal(r.comparisonPassed,true);assert.equal(result.stderr,'');for(const args of [['--baseline','a'],['--unknown','b'],['--dataset','a','--policy','b','--baseline','c','--candidate','d','--candidate','e']])assert.throws(()=>parseCompareFiles(args));
});
