import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {assessOperationalAlerts} from '../packages/operations/alerts.js';
import {verifiedOperationalAlertReport,alertProbeOptions} from '../scripts/operational-alert-probe.mjs';
const scope={organizationId:randomUUID(),projectId:randomUUID()};
function fixture(){return {projectId:scope.projectId,observedAt:new Date().toISOString(),worker:{state:'recent',ageSeconds:1},queue:{queued:0,running:0,overdue:0,expiredLeases:0},versionCapacity:{scope:'organization',organizationId:scope.organizationId,used:13,limit:1000,remaining:987},executionCapacity:{scope:'organization',organizationId:scope.organizationId,retained:{used:50,limit:10000,remaining:9950},active:{used:0,limit:10,remaining:10}},recent:{errors24h:99},privateUnusedField:'private-rule-and-model-output'};}
test('alert assessment distinguishes healthy operation from expected historical errors and redacts unused private data',()=>{const o=fixture(),before=JSON.stringify(o),r=assessOperationalAlerts(o,scope);assert.equal(r.status,'ok');assert.deepEqual(r.alerts,[]);assert.equal(r.readOnly,true);assert.equal(r.releasePermissionVerified,false);assert.equal(r.automatedRemediationPerformed,false);assert.equal(r.continuousMonitoringProven,false);assert.doesNotMatch(JSON.stringify(r),/private-rule|errors24h|model-output/);assert.equal(JSON.stringify(o),before);});
test('overdue runs, expired leases and missing or stale worker signals produce scoped critical alerts',()=>{for(const worker of [{state:'missing',ageSeconds:null},{state:'stale',ageSeconds:16},{state:'stale',ageSeconds:-1}]){const o=fixture();o.worker=worker;o.queue.overdue=1;o.queue.expiredLeases=1;const r=assessOperationalAlerts(o,scope);assert.equal(r.status,'critical');assert.deepEqual(r.alerts.map(x=>[x.code,x.scope]),[['worker-not-recent','service'],['execution-deadline-exceeded','project'],['worker-lease-expired','project']]);}});
test('organization capacity pressure is warning at ninety-five percent and critical when retained or version capacity is full',()=>{const o=fixture();for(const value of [o.versionCapacity,o.executionCapacity.retained]){value.used=value.limit*0.95;value.remaining=value.limit-value.used;}o.executionCapacity.active.used=10;o.executionCapacity.active.remaining=0;let r=assessOperationalAlerts(o,scope);assert.equal(r.status,'warning');assert.equal(r.alerts.length,3);assert.ok(r.alerts.every(x=>x.scope==='organization'));for(const value of [o.versionCapacity,o.executionCapacity.retained]){value.used=value.limit;value.remaining=0;}r=assessOperationalAlerts(o,scope);assert.equal(r.status,'critical');assert.ok(r.alerts.some(x=>x.code==='retained-capacity-full'));assert.ok(r.alerts.some(x=>x.code==='versions-capacity-full'));});
test('foreign scope and malformed operational evidence cannot become a reassuring alert assessment',()=>{for(const mutate of [o=>o.projectId=randomUUID(),o=>o.versionCapacity.organizationId=randomUUID(),o=>o.executionCapacity.organizationId=randomUUID(),o=>o.executionCapacity.scope='project',o=>o.queue.queued=-1,o=>o.queue.expiredLeases=NaN,o=>o.executionCapacity.retained.remaining=0,o=>o.versionCapacity.limit=2000,o=>o.worker.ageSeconds=16,o=>o.worker.state='unknown',o=>o.observedAt='yesterday']){const o=fixture();mutate(o);assert.throws(()=>assessOperationalAlerts(o,scope));}});
test('fractional heartbeat ages crossing the readiness boundary are classified consistently',()=>{const o=fixture();o.worker={state:'recent',ageSeconds:15};assert.equal(assessOperationalAlerts(o,scope).status,'ok');o.worker={state:'stale',ageSeconds:15.001};assert.equal(assessOperationalAlerts(o,scope).status,'critical');o.worker={state:'stale',ageSeconds:15};assert.throws(()=>assessOperationalAlerts(o,scope));});
test('the actual monitor report verifier rejects foreign, contradictory or unknown alerts and strips unused bodies',()=>{
 const r=assessOperationalAlerts(fixture(),scope);assert.deepEqual(verifiedOperationalAlertReport({...r,private:'private-output'},scope),r);
 for(const mutate of [x=>x.projectId=randomUUID(),x=>x.status='critical',x=>x.readOnly=false,x=>x.releasePermissionVerified=true,x=>x.alerts=[{code:'private-text',severity:'critical',scope:'service'}],x=>{x.alerts=[{code:'worker-not-recent',severity:'warning',scope:'service'}];x.status='warning';},x=>{x.alerts=[{code:'retained-capacity-high',severity:'warning',scope:'organization'},{code:'retained-capacity-full',severity:'critical',scope:'organization'}];x.status='critical';}]){const x=structuredClone(r);mutate(x);assert.throws(()=>verifiedOperationalAlertReport(x,scope));}
});
test('monitor arguments reject ambiguous selectors before any login or file read',()=>{assert.deepEqual(alertProbeOptions([]),{organizationIndex:0});assert.deepEqual(alertProbeOptions(['--organization-index','1']),{organizationIndex:1});for(const args of [['--organization-index','01'],['--organization-index','100'],['--organization-index','-1'],['--organization-index','1','--organization-index','0'],['--unknown','private-secret']])assert.throws(()=>alertProbeOptions(args));});
