package dev.agenttrust.gateway;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpMethod;
import java.util.Map;
import static org.junit.jupiter.api.Assertions.*;
class RoutePolicyTest {
 @Test void registryAndCampaignPathsAreFixedAndWritesRemainProtected(){assertTrue(RoutePolicy.allowed("/api/versions/agents",HttpMethod.POST));assertTrue(RoutePolicy.protectedPath("/api/versions/agents"));String id="11111111-1111-4111-8111-111111111111";assertTrue(RoutePolicy.allowed("/api/campaigns/"+id+"/comparison/"+id,HttpMethod.GET));assertTrue(RoutePolicy.allowed("/api/campaigns/"+id+"/reviews",HttpMethod.POST));assertTrue(RoutePolicy.allowed("/api/campaigns/"+id+"/evidence",HttpMethod.GET));assertFalse(RoutePolicy.allowed("/api/campaigns/"+id+"/evidence",HttpMethod.POST));assertFalse(RoutePolicy.allowed("/api/versions/agents/"+id,HttpMethod.POST));assertFalse(RoutePolicy.allowed("/api/campaigns/"+id+"/reviews",HttpMethod.GET));assertFalse(RoutePolicy.allowed("/api/versions/arbitrary",HttpMethod.GET));}
 @Test void developmentTrustAndReceiptRoutesAreAuthenticatedAndClosed(){String id="11111111-1111-4111-8111-111111111111";assertTrue(RoutePolicy.protectedPath("/api/gate-trust"));assertTrue(RoutePolicy.allowed("/api/gate-trust",HttpMethod.GET));assertFalse(RoutePolicy.allowed("/api/gate-trust",HttpMethod.POST));assertTrue(RoutePolicy.allowed("/api/campaigns/"+id+"/receipts",HttpMethod.POST));assertTrue(RoutePolicy.allowed("/api/campaigns/"+id+"/receipts/"+id,HttpMethod.GET));assertFalse(RoutePolicy.allowed("/api/campaigns/"+id+"/receipts/"+id,HttpMethod.POST));assertTrue(RoutePolicy.allowed("/api/campaigns/"+id+"/receipts/"+id+"/bundle",HttpMethod.GET));assertFalse(RoutePolicy.allowed("/api/campaigns/"+id+"/receipts/"+id+"/bundle",HttpMethod.POST));}
 @Test void internalAndArbitraryRoutesNeverProxy(){assertTrue(RoutePolicy.allowed("/api/runs",HttpMethod.POST));assertFalse(RoutePolicy.allowed("/internal/completions",HttpMethod.POST));assertFalse(RoutePolicy.allowed("/api/../actuator",HttpMethod.GET));assertFalse(RoutePolicy.allowed("/api/runs",HttpMethod.DELETE));assertFalse(RoutePolicy.allowed("/api/%72uns",HttpMethod.GET));}
 @Test void scopeComesFromCanonicalIdentityAndOnlyItsSessionIsForwarded(){String org="11111111-1111-4111-8111-111111111111";assertEquals(org+":"+org,RoutePolicy.quotaScope(Map.of("organizationId",org,"projectId",org)));assertThrows(IllegalArgumentException.class,()->RoutePolicy.quotaScope(Map.of("organizationId","attacker","projectId",org)));assertEquals("AGENTTRUST_STACK_SESSION=abcd.12",RoutePolicy.session("legacy=secret; AGENTTRUST_STACK_SESSION=abcd.12; unrelated=hidden"));}
 @Test void upstreamCannotChooseArbitraryRedirect(){assertTrue(GatewayController.validRedirect("/login/oauth2/code/keycloak","http://127.0.0.1:4320/"));assertFalse(GatewayController.validRedirect("/api/me","http://127.0.0.1:4320/"));assertFalse(GatewayController.validRedirect("/oauth2/authorization/keycloak","https://evil.invalid/"));}
}
