'use client';
import {useEffect,useRef,useState} from 'react';
import {detail,gate,identity,runs,RequestScope,type Identity,type Run,type Detail,type Gate} from '../lib/contracts';
const labels={pass:'통과',block:'차단',inconclusive:'판정 보류'};
async function json(path:string,init?:RequestInit){const response=await fetch('/backend/'+path,{...init,cache:'no-store'});if(!response.ok)throw Error(response.status===401?'로그인이 필요합니다.':response.status===403?'권한 또는 요청 검증을 확인해 주세요.':'요청을 완료하지 못했습니다.');return response.json() as Promise<unknown>}
export default function Workspace(){
 const [user,setUser]=useState<Identity|null>(null),[records,setRecords]=useState<Run[]>([]),[selected,setSelected]=useState<Detail|null>(null),[currentGate,setGate]=useState<Gate|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 const scope=useRef(new RequestScope()),selection=useRef(new RequestScope());
 async function refresh(generation:number){const u=identity(await json('me'));const rows=runs(await json('runs'));if(scope.current.current(generation)){setUser(u);setRecords(rows)}}
 useEffect(()=>{const generation=scope.current.next();refresh(generation).catch(()=>{}).finally(()=>{if(scope.current.current(generation))setLoading(false)});return ()=>{scope.current.next();selection.current.next()}},[]);
 useEffect(()=>{
  if(!selected||selected.state!=='queued'||!user)return;
  const record=selected,owner=user,generation=scope.current.capture(),chosen=selection.current.capture();let active=true;let timer:ReturnType<typeof setTimeout>;
  const current=()=>active&&scope.current.current(generation)&&selection.current.current(chosen);
  async function poll(){try{const updated=detail(await json('runs/'+record.id),owner,record.id);const value=gate(await json('runs/'+record.id+'/gate'),updated);if(current()){setSelected(updated);setGate(value);setRecords(rows=>rows.map(row=>row.id===updated.id?updated:row));if(updated.state!=='queued'){setMessage('워커 평가가 완료되었습니다.');return}}}catch{if(current())setMessage('워커 결과 조회를 다시 시도하고 있습니다.')}if(current())timer=setTimeout(poll,1000)}
  timer=setTimeout(poll,750);return ()=>{active=false;clearTimeout(timer)};
 },[selected?.id,selected?.state,user]);
 async function csrf(){const v=await json('csrf') as {token?:unknown};if(typeof v.token!=='string'||v.token.length>2048)throw Error('요청 검증을 준비하지 못했습니다.');return v.token}
 async function login(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const data=new FormData(event.currentTarget),generation=scope.current.next();selection.current.next();setUser(null);setRecords([]);setSelected(null);setGate(null);setBusy(true);setMessage('');const form=event.currentTarget;try{const token=await csrf();await json('login',{method:'POST',headers:{'X-CSRF-TOKEN':token},body:new URLSearchParams({username:String(data.get('username')),password:String(data.get('password'))})});form.reset();await refresh(generation)}catch(error){if(scope.current.current(generation))setMessage((error as Error).message)}finally{if(scope.current.current(generation))setBusy(false)}}
 async function logout(){if(busy)return;const generation=scope.current.next();selection.current.next();setSelected(null);setGate(null);setBusy(true);setMessage('');try{await json('logout',{method:'POST',headers:{'X-CSRF-TOKEN':await csrf()},body:'{}'});if(scope.current.current(generation)){setUser(null);setRecords([])}}catch(error){if(scope.current.current(generation))setMessage((error as Error).message)}finally{if(scope.current.current(generation))setBusy(false)}}
 async function select(record:Run){if(!user||busy)return;const generation=selection.current.next();setSelected(null);setGate(null);setMessage('');try{const result=detail(await json('runs/'+record.id),user,record.id);const g=gate(await json('runs/'+record.id+'/gate'),result);if(selection.current.current(generation)){setSelected(result);setGate(g)}}catch{if(selection.current.current(generation))setMessage('평가 근거를 확인하지 못했습니다. 다시 선택해 주세요.')}}
 async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!user||busy||user.role==='viewer')return;const data=new FormData(event.currentTarget),generation=scope.current.next();selection.current.next();setBusy(true);setMessage('');setSelected(null);setGate(null);try{const created=await json('runs',{method:'POST',headers:{'X-CSRF-TOKEN':await csrf(),'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({scenario:data.get('scenario'),requiresApproval:data.get('approval')==='on'})});const id=(created as {id:string}).id;const result=detail(created,user,id);const value=gate(await json('runs/'+id+'/gate'),result);await refresh(generation);if(scope.current.current(generation)){setSelected(result);setGate(value);setMessage(result.state==='queued'?'평가 요청을 저장했습니다. 워커 실행을 기다리고 있습니다.':'평가 결과를 저장했습니다.')}}catch{if(scope.current.current(generation))setMessage('평가 요청을 확인하지 못했습니다. 실행 목록을 확인해 주세요.')}finally{if(scope.current.current(generation))setBusy(false)}}
 async function review(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!user||user.role!=='admin'||!selected||busy)return;const data=new FormData(event.currentTarget),record=selected,generation=selection.current.next();setGate(null);setBusy(true);setMessage('');try{await json('runs/'+record.id+'/reviews',{method:'POST',headers:{'X-CSRF-TOKEN':await csrf()},body:JSON.stringify({decision:data.get('decision'),reason:data.get('reason')})});const value=gate(await json('runs/'+record.id+'/gate'),record);if(selection.current.current(generation)){setGate(value);setMessage('검토를 저장하고 현재 게이트를 다시 확인했습니다.')}}catch{if(selection.current.current(generation))setMessage('검토 결과를 확인하지 못했습니다. 현재 게이트를 다시 조회해 주세요.')}finally{if(selection.current.current(generation))setBusy(false)}}
 return <main><header><a className="brand" href="/">AgentTrust<span>평가와 릴리스 검토</span></a>{user&&<div className="account"><span>{user.username} · {user.role}</span><button disabled={busy} onClick={logout}>로그아웃</button></div>}</header>
 <section className="intro"><p className="eyebrow">ENTERPRISE EVALUATION WORKSPACE</p><h1>근거를 확인하고,<br/>릴리스를 결정하세요.</h1><p>합성 평가 결과와 관리자 검토를 함께 확인합니다.</p></section>
 <div role="status" aria-live="polite" className="message">{message|| (loading?'로그인 상태를 확인하고 있습니다.':'')}</div>
 {!user?<section className="card login"><h2>워크스페이스 로그인</h2><p>로컬 합성 계정으로 첫 평가 흐름을 확인하세요.</p><form onSubmit={login}><label>계정<input name="username" autoComplete="username" required maxLength={41}/></label><label>비밀번호<input name="password" type="password" autoComplete="current-password" required maxLength={72}/></label><button className="primary" disabled={busy||loading}>로그인</button></form></section>:<><section className="scope"><span>조직 {user.organizationId.slice(0,8)}</span><span>프로젝트 {user.projectId.slice(0,8)}</span><span>현재 권한 {user.role}</span></section><div className="grid"><section className="card"><h2>새 평가</h2><form onSubmit={create}><label>합성 시나리오<select name="scenario" aria-label="합성 시나리오"><option value="pass">필수 규칙 통과</option><option value="block">필수 규칙 실패</option><option value="missing_evidence">필수 근거 누락</option><option value="error">실행 오류</option></select></label><label className="check"><input name="approval" type="checkbox" defaultChecked/>관리자 승인 필요</label><button className="primary" disabled={busy||user.role==='viewer'}>평가 실행</button>{user.role==='viewer'&&<p>조회자 권한은 평가를 생성할 수 없습니다.</p>}</form></section><section className="card"><h2>최근 평가 <span className="count">{records.length}</span></h2>{records.length===0?<p>저장된 평가가 없습니다.</p>:<ul className="runs">{records.map(record=><li key={record.id}><button disabled={busy} onClick={()=>select(record)}><span>{record.scenario} · {record.id.slice(0,8)}</span><strong className={'badge '+record.decision}>{labels[record.decision]}</strong></button></li>)}</ul>}</section></div>
 {selected&&<section className="card evidence"><div className="title"><h2>평가 근거</h2><span className={'badge '+selected.decision}>{labels[selected.decision]}</span></div><p className="mono">실행 {selected.id}</p><table><caption>필수 규칙의 평가 결과</caption><thead><tr><th>규칙</th><th>결과</th><th>근거</th></tr></thead><tbody>{selected.result.rules.map(rule=><tr key={rule.id}><th>{rule.id}</th><td>{rule.status}</td><td>{rule.reason}</td></tr>)}</tbody></table><section className="gate"><h3>현재 릴리스 게이트</h3>{currentGate?<><strong>{currentGate.deploymentAllowed?'합성 릴리스 허용':'릴리스 허용 안 됨'}</strong><p>{currentGate.reason}</p><p className="mono">OPA/Rego 정책 {currentGate.policyVersion} · {currentGate.policyStatus}</p><p className="mono">{currentGate.policyDigest}</p><p>서명되지 않은 현재 조회 결과입니다. 실제 배포를 실행하지 않습니다.</p></>:<p>현재 게이트를 확인하지 못했습니다.</p>}</section>{user.role==='admin'&&selected.decision==='pass'&&<form onSubmit={review}><h3>관리자 검토</h3><label>결정<select name="decision" aria-label="결정"><option value="approved">승인</option><option value="rejected">반려</option></select></label><label>검토 사유<textarea name="reason" required maxLength={500}/></label><button disabled={busy}>검토 저장·게이트 확인</button></form>}</section>}</>}
 <footer>전환 단계: Next.js · TypeScript / Java 21 · Spring Boot / PostgreSQL. 현재 인증은 로컬 합성 계정이며 Python/FastAPI 워커가 합성 평가를 실행합니다.</footer></main>
}
