import {type Identity,type Decision,type Run,type Gate,gate} from './contracts.ts';
export type CaseDefinition={id:string;scenario:Run['scenario'];required:boolean};
export type Version={id:string;resource_key:string;version:number;content_sha256:string;created_at:string};
export type AgentVersion=Version&{definition:{contract:'fixed-scenarios-v1';provider:'synthetic'|'ollama'|'openai-compatible';description:string}};
export type DatasetVersion=Version&{definition:{contract:'fixed-scenarios-v1';cases:CaseDefinition[]}};
export type CampaignSummary={id:string;agent_version_id:string;dataset_version_id:string;requires_approval:boolean;created_at:string};
export type CaseEvidence={caseId:string;required:boolean;runId:string;scenario:Run['scenario'];provider:AgentVersion['definition']['provider'];state:Run['state'];decision:Decision};
export type Campaign=CampaignSummary&{organization_id:string;project_id:string;agent_content_sha256:string;dataset_content_sha256:string;agentVersion:AgentVersion;datasetVersion:DatasetVersion;cases:CaseEvidence[];state:Run['state'];decision:Decision};
export type Comparison={status:'no-regression'|'regression'|'inconclusive';newlyFailedRequiredCases:string[];unresolvedRequiredCases:string[];improvedRequiredCases:string[];deploymentAuthority:false};
function obj(v:unknown):Record<string,unknown>{if(!v||typeof v!=='object'||Array.isArray(v))throw Error('INVALID_CAMPAIGN');return v as Record<string,unknown>}
function str(v:unknown,max=300):string{if(typeof v!=='string'||v.length>max)throw Error('INVALID_CAMPAIGN');return v}
function uuid(v:unknown):string{const s=str(v,36);if(!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(s))throw Error('INVALID_CAMPAIGN');return s}
function bool(v:unknown):boolean{if(typeof v!=='boolean')throw Error('INVALID_CAMPAIGN');return v}
function choice<T extends string>(v:unknown,values:readonly T[]):T{if(typeof v!=='string'||!values.includes(v as T))throw Error('INVALID_CAMPAIGN');return v as T}
function hash(v:unknown):string{const s=str(v,64);if(!/^[a-f0-9]{64}$/.test(s))throw Error('INVALID_CAMPAIGN');return s}
function date(v:unknown):string{const s=str(v,50);if(!Number.isFinite(Date.parse(s)))throw Error('INVALID_CAMPAIGN');return s}
function bounded<T>(v:unknown,max:number,parse:(value:unknown)=>T):T[]{if(!Array.isArray(v)||v.length>max)throw Error('INVALID_CAMPAIGN');return v.map(parse)}
function unique(values:string[]){if(new Set(values).size!==values.length)throw Error('INVALID_CAMPAIGN')}
export function version(v:unknown):Version{const o=obj(v),key=str(o.resource_key,64);if(!/^[a-z][a-z0-9-]{2,63}$/.test(key)||!Number.isInteger(o.version)||(o.version as number)<1||(o.version as number)>1000000)throw Error('INVALID_CAMPAIGN');return {id:uuid(o.id),resource_key:key,version:o.version as number,content_sha256:hash(o.content_sha256),created_at:date(o.created_at)}}
export function versions(v:unknown):Version[]{const values=bounded(v,50,version);unique(values.map(x=>x.id));return values}
function scoped(v:Record<string,unknown>,user:Identity){if(v.organization_id!==user.organizationId||v.project_id!==user.projectId)throw Error('INVALID_SCOPE')}
export function agentVersion(v:unknown,user:Identity):AgentVersion{const o=obj(v),d=obj(o.definition);scoped(o,user);return {...version(v),definition:{contract:choice(d.contract,['fixed-scenarios-v1']),provider:choice(d.provider,['synthetic','ollama','openai-compatible']),description:str(d.description)}}}
export function datasetVersion(v:unknown,user:Identity):DatasetVersion{const o=obj(v),d=obj(o.definition);scoped(o,user);const cases=bounded(d.cases,8,value=>{const c=obj(value),id=str(c.id,64);if(!/^[a-z][a-z0-9-]{0,63}$/.test(id))throw Error('INVALID_CAMPAIGN');return {id,scenario:choice(c.scenario,['pass','block','missing_evidence','error']),required:bool(c.required)}});unique(cases.map(c=>c.id));if(!cases.length||!cases.some(c=>c.required))throw Error('INVALID_CAMPAIGN');return {...version(v),definition:{contract:choice(d.contract,['fixed-scenarios-v1']),cases}}}
export function campaignSummary(v:unknown):CampaignSummary{const o=obj(v);return {id:uuid(o.id),agent_version_id:uuid(o.agent_version_id),dataset_version_id:uuid(o.dataset_version_id),requires_approval:bool(o.requires_approval),created_at:date(o.created_at)}}
export function campaigns(v:unknown):CampaignSummary[]{const rows=bounded(v,50,campaignSummary);unique(rows.map(c=>c.id));return rows}
export function campaign(v:unknown,user:Identity,expectedId:string):Campaign{const o=obj(v),base=campaignSummary(v);scoped(o,user);if(base.id!==expectedId)throw Error('INVALID_SCOPE');const agent=agentVersion(o.agentVersion,user),dataset=datasetVersion(o.datasetVersion,user),a=hash(o.agent_content_sha256),d=hash(o.dataset_content_sha256);if(base.agent_version_id!==agent.id||base.dataset_version_id!==dataset.id||a!==agent.content_sha256||d!==dataset.content_sha256)throw Error('INVALID_VERSION_BINDING');
 const cases=bounded(o.cases,8,value=>{const c=obj(value);return {caseId:str(c.caseId,64),required:bool(c.required),runId:uuid(c.runId),scenario:choice(c.scenario,['pass','block','missing_evidence','error']),provider:choice(c.provider,['synthetic','ollama','openai-compatible']),state:choice(c.state,['queued','succeeded','failed']),decision:choice(c.decision,['pass','block','inconclusive'])}});unique(cases.map(c=>c.runId));if(cases.length!==dataset.definition.cases.length)throw Error('INVALID_CASE_BINDING');cases.forEach((c,i)=>{const declared=dataset.definition.cases[i];if(c.caseId!==declared.id||c.scenario!==declared.scenario||c.required!==declared.required||c.provider!==agent.definition.provider||c.state!=='succeeded'&&c.decision!=='inconclusive')throw Error('INVALID_CASE_BINDING')});
 const state=cases.some(c=>c.state==='queued')?'queued':cases.some(c=>c.state==='failed')?'failed':'succeeded';const required=cases.filter(c=>c.required);const decision:Decision=state!=='succeeded'?'inconclusive':required.some(c=>c.decision==='block')?'block':required.some(c=>c.decision==='inconclusive')?'inconclusive':'pass';const r=obj(o.result);if(o.state!==state||o.decision!==decision||r.state!==state||r.decision!==decision||r.executionEngine!=='java-campaign-aggregate')throw Error('INVALID_AGGREGATE');const rules=bounded(r.rules,8,obj);if(rules.length!==cases.length)throw Error('INVALID_AGGREGATE');rules.forEach((rule,i)=>{const c=cases[i],status=c.decision==='block'?'fail':c.decision;if(rule.id!=='case/'+c.caseId||rule.required!==c.required||rule.status!==status||typeof rule.reason!=='string'||rule.reason.length>500)throw Error('INVALID_AGGREGATE')});
 return {...base,organization_id:user.organizationId,project_id:user.projectId,agent_content_sha256:a,dataset_content_sha256:d,agentVersion:agent,datasetVersion:dataset,cases,state,decision};}
export function campaignGate(v:unknown,record:Campaign):Gate{return gate(v,{...record,provider:record.agentVersion.definition.provider,scenario:'pass'})}
function canonical(value:unknown):unknown{if(Array.isArray(value))return value.map(canonical);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([key,item])=>[key,canonical(item)]));return value}
async function verifiedHash<T extends AgentVersion|DatasetVersion>(value:T):Promise<T>{const content=new TextEncoder().encode(JSON.stringify(canonical(value.definition))),digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',content)),b=>b.toString(16).padStart(2,'0')).join('');if(digest!==value.content_sha256)throw Error('INVALID_VERSION_CONTENT');return value}
export async function verifiedAgentVersion(v:unknown,user:Identity):Promise<AgentVersion>{return verifiedHash(agentVersion(v,user))}
export async function verifiedDatasetVersion(v:unknown,user:Identity):Promise<DatasetVersion>{return verifiedHash(datasetVersion(v,user))}
export async function verifiedCampaign(v:unknown,user:Identity,id:string):Promise<Campaign>{const value=campaign(v,user,id);await Promise.all([verifiedHash(value.agentVersion),verifiedHash(value.datasetVersion)]);return value}
export function comparison(v:unknown,user:Identity,current:Campaign,baseline:string):Comparison{const o=obj(v);if(o.campaignId!==current.id||o.baselineCampaignId!==baseline||baseline===current.id||o.organizationId!==user.organizationId||o.projectId!==user.projectId||o.datasetVersionId!==current.dataset_version_id||o.datasetContentSha256!==current.dataset_content_sha256)throw Error('INVALID_COMPARISON_SCOPE');const c=obj(o.comparison),status=choice(c.status,['no-regression','regression','inconclusive']);if(c.deploymentAuthority!==false)throw Error('INVALID_COMPARISON');const required=new Set(current.cases.filter(x=>x.required).map(x=>x.caseId));function ids(v:unknown){const values=bounded(v,8,x=>str(x,64));unique(values);if(values.some(x=>!required.has(x)))throw Error('INVALID_COMPARISON');return values}const newlyFailedRequiredCases=ids(c.newlyFailedRequiredCases),unresolvedRequiredCases=ids(c.unresolvedRequiredCases),improvedRequiredCases=ids(c.improvedRequiredCases);if(newlyFailedRequiredCases.some(x=>improvedRequiredCases.includes(x))||status==='no-regression'&&(newlyFailedRequiredCases.length>0||unresolvedRequiredCases.length>0)||status==='regression'&&(!newlyFailedRequiredCases.length||unresolvedRequiredCases.length))throw Error('INVALID_COMPARISON');return {status,newlyFailedRequiredCases,unresolvedRequiredCases,improvedRequiredCases,deploymentAuthority:false}}
