export type Identity={username:string;organizationId:string;projectId:string;actorId:string;role:'admin'|'editor'|'viewer';identityProvider:'local-demo';runtime:'java21-spring-boot'};
export type Decision='pass'|'block'|'inconclusive';
export type Run={id:string;scenario:'pass'|'block'|'missing_evidence'|'error';requires_approval:boolean;state:'queued'|'succeeded'|'failed';decision:Decision;created_at:string};
export type Detail=Run & {organization_id:string;project_id:string;result:{state:string;decision:Decision;rules:{id:string;required:boolean;status:'pass'|'fail'|'inconclusive';reason:string}[];executionEngine:'java-synthetic'|'python-synthetic'|'python-unavailable'|'python-queued'}};
export type Gate={decision:Decision;deploymentAllowed:boolean;reason:string;signed:false;currentReviewRequired:boolean};
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw Error('INVALID_RESPONSE');return value as Record<string,unknown>}
function string(value:unknown,max=500):string{if(typeof value!=='string'||value.length>max)throw Error('INVALID_RESPONSE');return value}
function id(value:unknown):string{const text=string(value,36);if(!uuid.test(text))throw Error('INVALID_RESPONSE');return text}
function boolean(value:unknown):boolean{if(typeof value!=='boolean')throw Error('INVALID_RESPONSE');return value}
function choice<T extends string>(value:unknown,values:readonly T[]):T{if(typeof value!=='string'||!values.includes(value as T))throw Error('INVALID_RESPONSE');return value as T}
export function identity(value:unknown):Identity{const v=object(value);return {username:string(v.username,41),organizationId:id(v.organizationId),projectId:id(v.projectId),actorId:id(v.actorId),role:choice(v.role,['admin','editor','viewer']),identityProvider:choice(v.identityProvider,['local-demo']),runtime:choice(v.runtime,['java21-spring-boot'])}}
export function run(value:unknown):Run{const v=object(value);const at=string(v.created_at,50);if(!Number.isFinite(Date.parse(at)))throw Error('INVALID_RESPONSE');const result:Run={id:id(v.id),scenario:choice(v.scenario,['pass','block','missing_evidence','error']),requires_approval:boolean(v.requires_approval),state:choice(v.state,['queued','succeeded','failed']),decision:choice(v.decision,['pass','block','inconclusive']),created_at:at};if(result.state!=='succeeded'&&result.decision!=='inconclusive')throw Error('INVALID_RESPONSE');return result}
export function runs(value:unknown):Run[]{if(!Array.isArray(value)||value.length>50)throw Error('INVALID_RESPONSE');const rows=value.map(run);if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('INVALID_RESPONSE');return rows}
export function detail(value:unknown,user:Identity,expectedId:string):Detail{const v=object(value),base=run(value),r=object(v.result);if(base.id!==expectedId||v.organization_id!==user.organizationId||v.project_id!==user.projectId||r.decision!==base.decision||r.state!==base.state)throw Error('INVALID_SCOPE');if(!Array.isArray(r.rules)||r.rules.length<1||r.rules.length>100)throw Error('INVALID_RESPONSE');return {...base,organization_id:id(v.organization_id),project_id:id(v.project_id),result:{state:string(r.state,20),decision:base.decision,executionEngine:choice(r.executionEngine,['java-synthetic','python-synthetic','python-unavailable','python-queued']),rules:r.rules.map(raw=>{const rule=object(raw);return {id:string(rule.id,100),required:boolean(rule.required),status:choice(rule.status,['pass','fail','inconclusive']),reason:string(rule.reason)}})}}}
export function gate(value:unknown,record:Run):Gate{const v=object(value);if(v.signed!==false)throw Error('INVALID_GATE');const result:Gate={decision:choice(v.decision,['pass','block','inconclusive']),deploymentAllowed:boolean(v.deploymentAllowed),reason:string(v.reason),signed:false,currentReviewRequired:boolean(v.currentReviewRequired)};if(result.currentReviewRequired!==record.requires_approval||result.deploymentAllowed&&(result.decision!=='pass'||record.decision!=='pass'||record.state!=='succeeded'))throw Error('INVALID_GATE');return result}
export class RequestScope{private generation=0;next(){return ++this.generation}capture(){return this.generation}current(generation:number){return this.generation===generation}}
