export type Identity={username:string;organizationId:string;projectId:string;actorId:string;role:'admin'|'editor'|'viewer';identityProvider:'local-demo'|'keycloak';runtime:'java21-spring-boot'};
export type AuthInfo={identityProvider:'local-demo'|'keycloak';loginPath:'/backend/login'|'/backend/oauth2/authorization/keycloak';objectStorage:'disabled'|'minio'};
export type Decision='pass'|'block'|'inconclusive';
export type Run={id:string;scenario:'pass'|'block'|'missing_evidence'|'error';requires_approval:boolean;state:'queued'|'succeeded'|'failed';decision:Decision;created_at:string};
export type Detail=Run & {organization_id:string;project_id:string;result:{state:string;decision:Decision;rules:{id:string;required:boolean;status:'pass'|'fail'|'inconclusive';reason:string}[];executionEngine:'java-synthetic'|'python-synthetic'|'python-unavailable'|'python-queued'}};
export type Gate={decision:Decision;deploymentAllowed:boolean;reason:string;signed:false;currentReviewRequired:boolean;policyEngine:'opa-rego';policyStatus:'evaluated'|'unavailable';policyVersion:string;policyDigest:string};
const uuid=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i;
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw Error('INVALID_RESPONSE');return value as Record<string,unknown>}
function string(value:unknown,max=500):string{if(typeof value!=='string'||value.length>max)throw Error('INVALID_RESPONSE');return value}
function id(value:unknown):string{const text=string(value,36);if(!uuid.test(text))throw Error('INVALID_RESPONSE');return text}
function boolean(value:unknown):boolean{if(typeof value!=='boolean')throw Error('INVALID_RESPONSE');return value}
function choice<T extends string>(value:unknown,values:readonly T[]):T{if(typeof value!=='string'||!values.includes(value as T))throw Error('INVALID_RESPONSE');return value as T}
export function identity(value:unknown):Identity{const v=object(value);return {username:string(v.username,41),organizationId:id(v.organizationId),projectId:id(v.projectId),actorId:id(v.actorId),role:choice(v.role,['admin','editor','viewer']),identityProvider:choice(v.identityProvider,['local-demo','keycloak']),runtime:choice(v.runtime,['java21-spring-boot'])}}
export function authInfo(value:unknown):AuthInfo{const v=object(value),provider=choice(v.identityProvider,['local-demo','keycloak']);const path=provider==='keycloak'?'/backend/oauth2/authorization/keycloak':'/backend/login';if(v.loginPath!==path)throw Error('INVALID_AUTH_CONFIGURATION');return {identityProvider:provider,loginPath:path,objectStorage:choice(v.objectStorage,['disabled','minio'])}}
export type ArchivedEvidence={contentSha256:string;contentBytes:number;storageVersion:string};
export async function archivedEvidence(value:unknown,user:Identity,record:Detail):Promise<ArchivedEvidence>{const v=object(value);if(v.integrityVerified!==true||v.storageEngine!=='minio'||v.runId!==record.id||v.organizationId!==user.organizationId||v.projectId!==user.projectId)throw Error('INVALID_EVIDENCE');const hash=string(v.contentSha256,64),version=string(v.storageVersion,128),base64=string(v.contentBase64,22000);if(!/^[a-f0-9]{64}$/.test(hash)||!/^[A-Za-z0-9._-]{1,128}$/.test(version)||version==='null'||!Number.isInteger(v.contentBytes)||(v.contentBytes as number)<1||(v.contentBytes as number)>16384||!/^[A-Za-z0-9+/]+={0,2}$/.test(base64))throw Error('INVALID_EVIDENCE');const binary=atob(base64),content=Uint8Array.from(binary,c=>c.charCodeAt(0));if(content.length!==v.contentBytes)throw Error('INVALID_EVIDENCE');const digest=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',content)),byte=>byte.toString(16).padStart(2,'0')).join('');if(digest!==hash)throw Error('INVALID_EVIDENCE');const doc=object(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(content)));if(doc.schemaVersion!==1||doc.runId!==record.id||doc.organizationId!==user.organizationId||doc.projectId!==user.projectId||doc.scenario!==record.scenario)throw Error('INVALID_EVIDENCE');const checked=detail({...record,result:doc.result},user,record.id);if(JSON.stringify(checked.result)!==JSON.stringify(record.result))throw Error('INVALID_EVIDENCE');return {contentSha256:hash,contentBytes:content.length,storageVersion:version}}
export const identityLogoutUrl='http://127.0.0.1:4322/realms/agenttrust/protocol/openid-connect/logout?client_id=agenttrust-console&post_logout_redirect_uri=http%3A%2F%2F127.0.0.1%3A4320%2F';
export function logoutRedirect(value:unknown,provider:Identity['identityProvider']):string|null{const v=object(value);if(v.authenticated!==false)throw Error('INVALID_LOGOUT');if(provider==='keycloak'){if(v.logoutUrl!==identityLogoutUrl)throw Error('INVALID_LOGOUT');return identityLogoutUrl}return null}
export function run(value:unknown):Run{const v=object(value);const at=string(v.created_at,50);if(!Number.isFinite(Date.parse(at)))throw Error('INVALID_RESPONSE');const result:Run={id:id(v.id),scenario:choice(v.scenario,['pass','block','missing_evidence','error']),requires_approval:boolean(v.requires_approval),state:choice(v.state,['queued','succeeded','failed']),decision:choice(v.decision,['pass','block','inconclusive']),created_at:at};if(result.state!=='succeeded'&&result.decision!=='inconclusive')throw Error('INVALID_RESPONSE');return result}
export function runs(value:unknown):Run[]{if(!Array.isArray(value)||value.length>50)throw Error('INVALID_RESPONSE');const rows=value.map(run);if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('INVALID_RESPONSE');return rows}
export function detail(value:unknown,user:Identity,expectedId:string):Detail{const v=object(value),base=run(value),r=object(v.result);if(base.id!==expectedId||v.organization_id!==user.organizationId||v.project_id!==user.projectId||r.decision!==base.decision||r.state!==base.state)throw Error('INVALID_SCOPE');if(!Array.isArray(r.rules)||r.rules.length<1||r.rules.length>100)throw Error('INVALID_RESPONSE');return {...base,organization_id:id(v.organization_id),project_id:id(v.project_id),result:{state:string(r.state,20),decision:base.decision,executionEngine:choice(r.executionEngine,['java-synthetic','python-synthetic','python-unavailable','python-queued']),rules:r.rules.map(raw=>{const rule=object(raw);return {id:string(rule.id,100),required:boolean(rule.required),status:choice(rule.status,['pass','fail','inconclusive']),reason:string(rule.reason)}})}}}
export function gate(value:unknown,record:Run):Gate{const v=object(value);if(v.signed!==false)throw Error('INVALID_GATE');const result:Gate={decision:choice(v.decision,['pass','block','inconclusive']),deploymentAllowed:boolean(v.deploymentAllowed),reason:string(v.reason),signed:false,currentReviewRequired:boolean(v.currentReviewRequired),policyEngine:choice(v.policyEngine,['opa-rego']),policyStatus:choice(v.policyStatus,['evaluated','unavailable']),policyVersion:string(v.policyVersion,40),policyDigest:string(v.policyDigest,71)};if(!/^\d+\.\d+\.\d+$/.test(result.policyVersion)||!/^sha256:[a-f0-9]{64}$/.test(result.policyDigest)||result.policyStatus==='unavailable'&&result.deploymentAllowed)throw Error('INVALID_POLICY');if(result.currentReviewRequired!==record.requires_approval||result.deploymentAllowed&&(result.decision!=='pass'||record.decision!=='pass'||record.state!=='succeeded'))throw Error('INVALID_GATE');return result}
export class RequestScope{private generation=0;next(){return ++this.generation}capture(){return this.generation}current(generation:number){return this.generation===generation}}

export type SimilarMatch={runId:string;scenario:Run['scenario'];state:Run['state'];decision:Decision;score:number};
export function similarEvidence(value:unknown,user:Identity,record:Detail):SimilarMatch[]{const v=object(value);if(v.runId!==record.id||v.organizationId!==user.organizationId||v.projectId!==user.projectId||v.featureVersion!=='rule-features-v1'||v.dimensions!==64||v.searchEngine!=='pgvector-cosine'||v.deploymentAuthority!==false||!Array.isArray(v.matches)||v.matches.length>5)throw Error('INVALID_SIMILARITY');const seen=new Set<string>();let previous=1;return v.matches.map(raw=>{const m=object(raw),runId=id(m.runId),score=m.score;if(runId===record.id||seen.has(runId)||typeof score!=='number'||!Number.isFinite(score)||score<0||score>1||score>previous+1e-6)throw Error('INVALID_SIMILARITY');seen.add(runId);previous=score;const state=choice(m.state,['succeeded','failed']),decision=choice(m.decision,['pass','block','inconclusive']);if(state==='failed'&&decision!=='inconclusive')throw Error('INVALID_SIMILARITY');return {runId,scenario:choice(m.scenario,['pass','block','missing_evidence','error']),state,decision,score}})}
