import {campaignGate,type Campaign,type CampaignArchive} from './campaign-contracts.ts';
import {type Identity,type Gate} from './contracts.ts';
export type Receipt={receiptId:string;issuedAt:string;note:string;keyId:string;observedGate:Gate;currentDeploymentAuthority:false};
function object(value:unknown):Record<string,unknown>{if(!value||typeof value!=='object'||Array.isArray(value))throw Error('INVALID_RECEIPT');return value as Record<string,unknown>}
function text(value:unknown,max:number){if(typeof value!=='string'||value.length>max)throw Error('INVALID_RECEIPT');return value}
function uuid(value:unknown){const v=text(value,36);if(!/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(v))throw Error('INVALID_RECEIPT');return v}
function hash(value:unknown){const v=text(value,64);if(!/^[a-f0-9]{64}$/.test(v))throw Error('INVALID_RECEIPT');return v}
function bytes(value:unknown,max:number){const encoded=text(value,22000);if(!/^[A-Za-z0-9+/]+={0,2}$/.test(encoded))throw Error('INVALID_RECEIPT');const result=Uint8Array.from(atob(encoded),x=>x.charCodeAt(0));if(!result.length||result.length>max||btoa(String.fromCharCode(...result))!==encoded)throw Error('INVALID_RECEIPT');return result}
async function digest(value:Uint8Array<ArrayBuffer>){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',value)),x=>x.toString(16).padStart(2,'0')).join('')}
export async function verifiedReceipt(value:unknown,trustValue:unknown,user:Identity,record:Campaign,archive:CampaignArchive):Promise<Receipt>{
 const frame=object(value),trust=object(trustValue),domain='agenttrust-local-development',keyId=hash(trust.keyId),publicKey=bytes(trust.publicKeySpkiBase64,44);
 if(publicKey.length!==44||await digest(publicKey)!==keyId||trust.signatureAlgorithm!=='Ed25519'||trust.trustDomain!==domain||trust.productionKey!==false||frame.keyId!==keyId||frame.signatureAlgorithm!=='Ed25519'||frame.trustDomain!==domain||frame.currentDeploymentAuthority!==false||frame.signatureVerified!==true||frame.organizationId!==user.organizationId||frame.projectId!==user.projectId||frame.campaignId!==record.id)throw Error('INVALID_RECEIPT');
 const receiptId=uuid(frame.receiptId),payload=bytes(frame.payloadBase64,16384),signature=bytes(frame.signatureBase64,64);if(payload.length!==frame.payloadBytes||signature.length!==64||await digest(payload)!==hash(frame.payloadSha256))throw Error('INVALID_RECEIPT');
 const key=await crypto.subtle.importKey('spki',publicKey,{name:'Ed25519'},false,['verify']);if(!await crypto.subtle.verify('Ed25519',key,signature,payload))throw Error('INVALID_RECEIPT_SIGNATURE');
 const doc=object(JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(payload))),issuedAt=text(doc.issuedAt,50),note=text(doc.note,200);uuid(doc.actorId);
 if(Object.keys(doc).length!==21||doc.schemaVersion!==1||doc.kind!=='campaign-gate-observation'||doc.trustDomain!==domain||doc.currentDeploymentAuthority!==false||doc.receiptId!==receiptId||doc.campaignId!==record.id||doc.organizationId!==user.organizationId||doc.projectId!==user.projectId||!/^\d{4}-\d\d-\d\dT.*Z$/.test(issuedAt)||!Number.isFinite(Date.parse(issuedAt))||doc.agentVersionId!==record.agent_version_id||doc.datasetVersionId!==record.dataset_version_id||doc.agentContentSha256!==record.agent_content_sha256||doc.datasetContentSha256!==record.dataset_content_sha256||doc.evaluationState!==record.state||doc.evaluationDecision!==record.decision||record.state==='queued')throw Error('INVALID_RECEIPT_BINDING');
 const stored=object(doc.campaignArchive);if(Object.keys(stored).length!==3||stored.contentSha256!==archive.contentSha256||stored.contentBytes!==archive.contentBytes||stored.storageVersion!==archive.storageVersion||!Array.isArray(doc.childArchives)||doc.childArchives.length!==archive.childArchives.length)throw Error('INVALID_RECEIPT_ARCHIVE');
 doc.childArchives.forEach((raw,i)=>{const child=object(raw),expected=archive.childArchives[i];if(Object.keys(child).length!==4||child.runId!==expected.runId||child.contentSha256!==expected.contentSha256||child.contentBytes!==expected.contentBytes||child.storageVersion!==expected.storageVersion)throw Error('INVALID_RECEIPT_ARCHIVE')});
 const observedGate=campaignGate(doc.observedGate,record);if(observedGate.policyStatus!=='evaluated')throw Error('INVALID_RECEIPT_POLICY');
 if(doc.latestReview!==null){const review=object(doc.latestReview);uuid(review.id);uuid(review.actorId);if(Object.keys(review).length!==6||!['approved','rejected'].includes(String(review.decision))||!Number.isInteger(review.sequence)||(review.sequence as number)<1||typeof review.policyVersion!=='string'||typeof review.policyDigest!=='string'||review.decision==='rejected'&&observedGate.deploymentAllowed)throw Error('INVALID_RECEIPT_REVIEW');if(observedGate.deploymentAllowed&&record.requires_approval&&(review.decision!=='approved'||review.policyVersion!==observedGate.policyVersion||review.policyDigest!==observedGate.policyDigest))throw Error('INVALID_RECEIPT_REVIEW');
 }else if(observedGate.deploymentAllowed&&record.requires_approval)throw Error('INVALID_RECEIPT_REVIEW');
 return {receiptId,issuedAt,note,keyId,observedGate,currentDeploymentAuthority:false};
}
export function receiptIds(value:unknown):string[]{if(!Array.isArray(value)||value.length>50)throw Error('INVALID_RECEIPT');const ids=value.map(v=>uuid(object(v).id));if(new Set(ids).size!==ids.length)throw Error('INVALID_RECEIPT');return ids}
