import {inspectOperationalObservation} from './observation-evidence.js';

const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const labels={ok:'경고 없는 표본',warning:'주의 경고',critical:'심각 경고',incomplete:'미완료 기록'};
const failures={'interrupted':'요청한 중단','authentication-denied':'인증 요청 거부','access-denied':'접근 요청 거부','rate-limited':'요청 제한','service-unavailable':'서비스 오류 응답','request-rejected':'요청 거부','request-timeout':'요청 시간 초과','transport-failed':'요청 전송 실패','response-invalid':'응답 처리·검증 실패','session-scope-invalid':'조직·역할 범위 불일치','session-unconfirmed':'세션 수신 미확인','checkpoint-write-failed':'기록 저장 실패','session-cleanup-unconfirmed':'세션 정리 미확인','operation-failed':'분류하지 못한 실패'};
export function renderOperationalObservationReport(report,expected={}){
 const s=inspectOperationalObservation(report,expected),diagnostic=(label,code)=>`<tr><th scope="row">${label}</th><td>${code?escape(failures[code])+' <code>'+escape(code)+'</code>':'기록된 진단 없음'}</td></tr>`;
 const rows=report.samples.map((sample,index)=>`<tr><td>${index+1}</td><td><time>${escape(sample.at)}</time></td><td>${escape(labels[sample.assessment.status])}</td><td>${sample.assessment.alerts.length?sample.assessment.alerts.map(a=>'<code>'+escape(a.code)+'</code>').join('<br>'):'경고 코드 없음'}</td></tr>`).join('');
 const counts=['ok','warning','critical'].map(status=>`<div class="count ${status}"><span>${labels[status]}</span><strong>${s.sampleStatusCounts[status]}</strong></div>`).join('');
 const html=`<!doctype html>
<html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; form-action 'none'"><title>AgentTrust 운영 관찰 기록</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f7fb;color:#172333;font:16px/1.65 system-ui,sans-serif}main{max-width:1040px;margin:36px auto;padding:0 24px 48px}header,section{background:white;border:1px solid #d9e1ec;border-radius:14px;padding:24px;margin:18px 0}h1{font-size:30px;line-height:1.3;margin:8px 0 18px}h2{font-size:21px;margin:0 0 12px}.brand{color:#385681;font-weight:700;letter-spacing:.05em}.status{display:inline-block;border:1px solid #77889f;border-radius:6px;padding:4px 10px;font-weight:700}.critical,.incomplete{color:#9d292b}.warning{color:#855306}.ok{color:#286348}.note{color:#43566d}.counts{display:flex;flex-wrap:wrap;gap:14px}.count{flex:1;min-width:160px;border:1px solid #d9e1ec;border-radius:8px;padding:12px}.count strong{display:block;font-size:28px}table{width:100%;border-collapse:collapse;table-layout:fixed}caption{text-align:left;font-weight:700;padding:8px 0}th,td{border-bottom:1px solid #d9e1ec;text-align:left;vertical-align:top;padding:10px;overflow-wrap:anywhere}th{font-weight:600}code,time{font-size:13px}dl{margin:0}dt{font-weight:600}dd{margin:0 0 12px;overflow-wrap:anywhere}footer{font-size:14px;color:#43566d}@media(max-width:600px){main{padding:0 12px}header,section{padding:18px}h1{font-size:25px}table{font-size:13px}th,td{padding:6px}}@media print{body{background:white}main{max-width:none;margin:0;padding:0}header,section{break-inside:avoid;border-radius:0}table{font-size:12px}}
</style></head><body><main><header><div class="brand">AGENTTRUST · 보관한 관찰 기록</div><h1>운영 관찰 기록</h1><p class="status ${s.status}">${escape(labels[s.status])}</p><p class="note">이 페이지는 입력 JSON의 구조와 선언을 검사한 과거 기록입니다. 서명 인증·실제 실행·현재 건강 상태·현재 배포 승인을 확인하지 않았습니다.</p></header>
<section aria-labelledby="summary"><h2 id="summary">기록된 완료 범위</h2><p>검증된 표본 <strong>${s.samples}</strong> / 요청한 표본 <strong>${s.requestedSamples}</strong> · 간격 ${s.intervalSeconds}초</p><div class="counts">${counts}</div><p>${s.samples?'표본 사이의 연속 상태와 서비스 가동 시간을 보장하지 않습니다.':'검증된 표본이 없습니다. 정상 운영으로 판단하지 않습니다.'}</p><p>완료 선언: ${s.recordedCompleted?'완료':'미완료'} · 세션 범위 확인 선언: ${s.recordedSessionScopeVerified?'확인':'미확인'} · 자체 세션 종료 선언: ${s.recordedSessionLoggedOut?'종료':'미확인'}</p></section>
<section aria-labelledby="scope"><h2 id="scope">기록의 조직·프로젝트 범위</h2><dl><dt>조직 UUID</dt><dd><code>${escape(s.organizationId)}</code></dd><dt>프로젝트 UUID</dt><dd><code>${escape(s.projectId)}</code></dd><dt>입력한 기대 범위 대조</dt><dd>${s.expectedScopeVerified?'기대 조직·프로젝트와 일치':'기대 범위를 지정하지 않음'}</dd><dt>첫 표본 / 마지막 표본</dt><dd>${escape(s.firstSampleAt??'표본 없음')} / ${escape(s.lastSampleAt??'표본 없음')}</dd><dt>최종 기록 시각</dt><dd>${escape(s.finishedAt??'최종 시각 없음')}</dd></dl><p class="note">범위 일치는 현재 사용자의 권한이나 기록의 진위를 인증하지 않습니다.</p></section>
<section aria-labelledby="diagnostics"><h2 id="diagnostics">기록된 실패 진단</h2><table><caption>요청·정리·저장 진단을 구분합니다</caption><tbody>${diagnostic('관찰 요청',s.recordedFailureCode)}${diagnostic('세션 정리',s.recordedCleanupFailureCode)}${diagnostic('최종 기록 저장',s.recordedReportWriteFailureCode)}</tbody></table><p class="note">진단의 진위, 세션 취소 주체와 근본 원인은 별도로 확인해야 합니다. 진단 없는 과거 기록에 새 원인을 추정하지 않습니다.</p></section>
<section aria-labelledby="samples"><h2 id="samples">관찰 표본</h2><table><caption>기록된 시각과 고정 경고 코드</caption><thead><tr><th scope="col">번호</th><th scope="col">기록 시각</th><th scope="col">상태</th><th scope="col">경고 코드</th></tr></thead><tbody>${rows||'<tr><td colspan="4">검증된 표본 없음</td></tr>'}</tbody></table></section><footer>네트워크 요청이나 스크립트 없이 열 수 있는 정적 보고서입니다. 원문 오류·응답 메시지·접근 키·세션 쿠키는 포함하지 않습니다.</footer></main></body></html>`;
 return {html,inspection:s};
}
